name: breizh_blok_auth
publish_to: "none"
version: 1.0.0

resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  auth0_flutter: ^1.14.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0

dev_dependencies:
  breizh_blok_lint:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  mocktail: ^1.0.4

flutter:
