name: breizh_blok_mobile
description: Application r√©pertoriant des blocs d'escalade en Bretagne
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.20.0+2.20.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  breizh_blok_analytics:
  breizh_blok_api_generated:
  breizh_blok_auth:
  breizh_blok_share_content:
  breizh_blok_url_launcher:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dio_http2_adapter: ^2.6.0
  drift: ^2.29.0
  envied: ^1.3.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_cache_manager: ^3.4.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_svg: ^2.2.0
  fpdart: ^1.1.1
  freezed_annotation: ^3.0.0
  go_router: ^17.0.0
  http: ^1.5.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  location: ^8.0.1
  map_launcher: ^4.4.2
  mapbox_maps_flutter: ^2.12.0
  path: ^1.8.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.4.0
  reactive_forms: ^18.1.1
  riverpod_annotation: ^3.0.0
  sentry_flutter: ^9.6.0
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.39
  syncfusion_flutter_sliders: ^30.2.7
  upgrader: ^12.3.0

dev_dependencies:
  bloc_test: ^10.0.0
  breizh_blok_lint:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  drift_dev: ^2.29.0
  envied_generator: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^3.0.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  sentry_dart_plugin: ^3.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/cluster/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

sentry:
  upload_debug_symbols: true
  upload_sources: true
  wait_for_processing: true
  dart_symbol_map_path: obfuscation.map.json
  ignore_missing: true
