name: breizh_blok_share_content
publish_to: "none"
version: 1.0.0

resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  breizh_blok_lint:
  flutter_test:
    sdk: flutter
    
flutter: